language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: jdjRO6Pe+Xb+tL6qUYziL0mrcnj2thdeNg1ycpMCJfudiH3s+YHmkpuMLk3xCf9z6/JDmvzRxtZnZpDd9AoJ7Ii155gnbRvQG07Yu7k62ySx6B++A4kCmZwLK/ofLzWCL/fjU7Sotdt6CBXLP3kFPSKrmiEVC3FE3qTHPtxhjAtawpRuw74Flynpq6jJ2sNtcAt0Kws3zsrGr8Vu1PMyuMi8CmxGnkfH2BMg/+YKMnNrKsVlcsD58PThTl/pEzhQRJwBOkUxNl7v9Lt3Q/bfKyt1dR9uw9gHqvrya3s67teCGgC3UDNqid8ezxojQxJcuier1vMZSjuKNiaOM95EdSnG8rO11j45iX010xrBGPupFZYQEfx18onapzANg7/mwgyeQ9zN/BWy/tJHL1jcWB1M8WMvi04M3cpZwWKbcD29M7TSlbsuFimChegnZaOxLqu0Th1WfHDwTaG7ztwU8R8XvXETYNQquXev69UA0jjSVLgUnKgllBOYSri2Aen28RyrDMhYaQaMAl3o8t5uAYdUc04Tcy6xZPh6YcfMTeW4cS3j1roSNNhVbSs2gAy4Ewl718f3Sof4mhNLZk5fzpLQeS4/wSE7rkp5JtogMiBeGi8P9vjpK3DxPdadwjw1X6pMTgZpmS2t0V19G2twg9Lw4S9pFYzp0VJ0CCQppmM=
  app: frozen-shore-58330
  on:
    repo: Naxus28/jquery-express-blog
