import User from '../resources/user/userModel';
import { createJwt } from '../helpers/authHelpers';
import { DatabaseException } from '../../exceptions/exceptionClasses';
import { errorHandler } from '../helpers/apiHelpers';

export default (req, res) => {
	User.findOne({email: req.body.email})
	  .select('-password') // removes password from returned query
	  .populate('blogPosts')
	  .exec((err, user) => {
	    // err.codeName is generated by mongoose/mongo 
	    if (err) return errorHandler(err.codeName, DatabaseException, next);

	    // send the user along with the jwt
	    res.json({ 
	    	user,
	    	jwt: createJwt(req.user.email)
	    });
	  });


};