import User from './userModel';
import { DatabaseException } from '../../../exceptions/exceptionClasses';
import { errorHandler } from '../../helpers/apiHelpers';
import _ from 'lodash';

/**
 * create user
 * @param  {Object} req  
 * @param  {Object} res 
 * @param  {Function} next
 * @return {undefined}       
 */
const addUser = (req, res, next) => {
  new User(req.body)
    .save((err, user) => {
      if (err) return errorHandler(err, DatabaseException, next);
      res.json(user.serializeResponse(user));
    });
};


/**
 * get users
 * @param  {Object} req 
 * @param  {Object} res 
 * @param  {Function} next
 * @return {undefined}       
 */
const getUsers = (req, res, next) => {
  User.find({})
    .select('-password') // removes password from returned query
    .populate('blogPosts')
    .exec((err, user) => {
      // err.codeName is generated by mongoose/mongo 
      if (err) return errorHandler(err.codeName, DatabaseException, next);
      res.json(user);
    });
};


/**
 * get user
 * this controller is used in a protected route: 
 * before passing control flow to this controller,
 * the route checks if client sent jwt
 * @param  {Object} req 
 * @param  {Object} res 
 * @param  {Function} next
 * @return {undefined}       
 */
const getUser = (req, res, next) => {
  User.findOne({_id: req.params.id})
    .select('-password') // removes password from returned query
    .populate('blogPosts')
    .exec((err, user) => {
      // err.codeName is generated by mongoose/mongo 
      if (err) return errorHandler(err.codeName, DatabaseException, next);
      res.json(user); 
    });
};


const deleteUser = (req, res, next) => {
  User.findOneAndRemove({_id: req.params.id}, (err, user) => {
    if (err) return errorHandler(err, ApiException, next);

    if (!Object.keys(user).length) return errorHandler({
        message: 'Resource not found', 
        status: 404
      }, DatabaseException, next);

    // need the line below to trigger User.pre('remove', ()=>{}) hook on the model
    // which removes blog posts associated with this user
    user.remove();
    
    res.json({message: `User was successfuly deleted.`});
  });
};

export {
  addUser,
  deleteUser,
  getUsers,
  getUser
};